### ISSUE TITLE
Doesn't work for this case

### ISSUE THREAD

**Issue by lepinekong** [lpubsppop01/vscode-auto-timestamp#1]
I have a .red extension file with

Red [
    Dates: [
        // Created: 
        // Last modified: 
    ]
]

It doesn't update on save.

**Comment by lpubsppop01** [comment]
Hi, @lepinekong.
Thanks for your feedback.

In default setting, one space is required after colon like this:
```
Red [
Dates: [
// Created: 
// Last modified: 
]
]
```

Please try the above way, or change regex pattern `lpubsppop01.autoTimeStamp.modifiedTimeStart` and `lpubsppop01.autoTimeStamp.birthTimeStart` in settings.

**Comment by StridingDragon** [comment]
Yeah, this does not work at all! What's up with that?
Using it in a C file in VSCode 1.34.0 on OSX 10.14.5 and it does absolutely nothing, even with a space after the colon. It doesn't even populate the fields and it certainly doesn't update them.

```
// Created: 
// Last modified: 
```

**Comment by lpubsppop01** [comment]
I will close this issue. If you reproduce again, please let me know.
