### ISSUE TITLE
Replace inline ?

### ISSUE THREAD

**Issue by yabdab** [lpubsppop01/vscode-auto-timestamp#11]
What regex pattern can I use to allow this to happen ...

```blade
{{-- MODIFIED: [ 2022-04-20 02:51:45 PM ] --}}
{{-- some other comment --}}
````

instead of this ...

```blade
{{-- MODIFIED: [ 2022-04-20 02:51:45 PM ] 
{{-- some other comment --}}
```

**Comment by lpubsppop01** [comment]
Hi @yabdab.
Thank you for your feedback, and sorry for the very late reply.

If you are still using this extension, please try the following:
```
{
    "lpubsppop01.autoTimeStamp.momentFormat": "YYYY/MM/DD HH:mm:ss A",
    "lpubsppop01.autoTimeStamp.modifiedTimeStart": "MODIFIED: \\[ ",
    "lpubsppop01.autoTimeStamp.modifiedTimeEnd": " \\]"
}
```

If you were using workspace settings, you may have been affected by [#9](https://github.com/lpubsppop01/vscode-auto-timestamp/issues/9).
Please try after updating to v0.0.5.
