### ISSUE TITLE
Problem with single line block comments

### ISSUE THREAD

**Issue by claudio-salvio** [lpubsppop01/vscode-auto-timestamp#13]
Hello @lpubsppop01 

It would appear that the plugin breaks single line block comments.

For example:
```
<!-- Last modified: -->
```
becomes:
```
<!-- Last modified: 2023/03/18 08:10:00:00
```
Could you fix it?

Best regards,
Claudio

PS: Thanks for the extension! 👏

**Comment by lpubsppop01** [comment]
Hello, @claudio-salvio.
Thank you for your feedback.

The following settings affect where the date and time are written:
```json
{
    "lpubsppop01.autoTimeStamp.birthTimeEnd": "$",
    "lpubsppop01.autoTimeStamp.birthTimeStart": "[cC]reated *: ",
    "lpubsppop01.autoTimeStamp.modifiedTimeEnd": "$",
    "lpubsppop01.autoTimeStamp.modifiedTimeStart": "[lL]ast[ -][mM]odified *: "
}
```

`modifiedTimeEnd` is `$` by default, so `-->` will be overwritten.
If `modifiedTimeEnd` is a pattern that also matches `-->`, it will not be overwritten.

For example:
```json
{
    "lpubsppop01.autoTimeStamp.modifiedTimeEnd": "( *-->|$)"
}
```

Please try it.

**Comment by claudio-salvio** [comment]
Hello, @lpubsppop01 

Thank you for your prompt response !
It works correctly by modifying `modifiedTimeEnd` the way you suggested.

Kind regards,
Claudio
