### ISSUE TITLE
[RFE] Add support to configure by file type or by extension

### ISSUE THREAD

**Issue by claudio-salvio** [lpubsppop01/vscode-auto-timestamp#14]
Hi @lpubsppop01,

I think it would be very useful if the extension allows us to specify the **configuration by file type or by extension**.
I mean something like what the [*Power Header*](https://marketplace.visualstudio.com/items?itemName=epivision.vscode-file-header) extension allows to do.
For more information, see the examples at: [*Use Case Examples (extending default settings)*](https://marketplace.visualstudio.com/items?itemName=epivision.vscode-file-header#use-case-examples-extending-default-settings)

Below is an example of a segment of a `settings.json` file as I imagine it could look like with the proposed modification:

```json
    "lpubsppop01.autoTimeStamp.fileNamePattern": "",

    "[plaintext]": {
        "lpubsppop01.autoTimeStamp.birthTimeEnd": "$",
        "lpubsppop01.autoTimeStamp.birthTimeStart": "[cC]reated *: ",
        "lpubsppop01.autoTimeStamp.lineLimit": "5",

        "lpubsppop01.autoTimeStamp.modifiedTimeEnd": "$",
        "lpubsppop01.autoTimeStamp.modifiedTimeStart": "[lL]ast[ -][mM]odified *: "

        "lpubsppop01.autoTimeStamp.momentFormat": "DD/MM/YYYY HH:mm:ss",
    }
    "[md]": {
        "lpubsppop01.autoTimeStamp.birthTimeEnd": " *-->",
        "lpubsppop01.autoTimeStamp.birthTimeStart": "<!-- *[cC]reated:  *: ",
        "lpubsppop01.autoTimeStamp.lineLimit": "10",

        "lpubsppop01.autoTimeStamp.modifiedTimeEnd": " *-->",
        "lpubsppop01.autoTimeStamp.modifiedTimeStart": "<!-- *[lL]ast[ -][mM]odified *: "

        "lpubsppop01.autoTimeStamp.momentFormat": "YYYY.MM.DD HH:mm:ss",
    }
```

🙏 Thank you for sharing this useful extension.

Kind regards,
Claudio Salvio

**Comment by lpubsppop01** [comment]
Thanks for your feedback, @claudio-salvio.

I checked and it seems that per language (file type) settings are now supported by the SDK and easily available from extensions.
- [Allow Extensions To Contribute Language Specific Settings · Issue #26707 · microsoft/vscode](https://github.com/Microsoft/vscode/issues/26707)

As you say, it would be useful and intuitive to be able to override the settings in this extension for each language.
I will update this later, so please try it.
