### ISSUE TITLE
only update the modified timestamp when the file was actually edited

### ISSUE THREAD

**Issue by vickkhera** [lpubsppop01/vscode-auto-timestamp#15]
If I open a file and save it, the timestamp gets updated. It should only do this if the buffer was modified and needed saving.

**Comment by lpubsppop01** [comment]
Thanks for your feedback, @vickkhera.

This extension receives the file's pre-save event and updates the timestamp in the content, and VS Code will update the file even if there are no changes on save.
Thus, the behavior you pointed out is as intended.

There was some requests to add a setting not to update the file if it has not been changed, but it seems that it was not adopted.
- [Add setting to configure if saving non-dirty file should touch the file · Issue #41812 · microsoft/vscode (github.com)](https://github.com/microsoft/vscode/issues/41812)
- [Request: only save file if it has changed · Issue #54651 · microsoft/vscode](https://github.com/Microsoft/vscode/issues/54651)
