### ISSUE TITLE
Achieve specific block comment

### ISSUE THREAD

**Issue by githuppi** [lpubsppop01/vscode-auto-timestamp#18]
Hello I am struggling to find out how to achieve the following comment:

```
/* Created: 09.10.2023 12:24:41 */
/* Last modified: 16.10.2023 10:02:34 */
```

Can you please guide me through the settings of Auto Time Stamp?

Kind regards

**Comment by lpubsppop01** [comment]
Hi, @githuppi.
Thank you for using this extension.

Please try the following settings:
```json
{
    "lpubsppop01.autoTimeStamp.birthTimeEnd": "($| \\*/)",
    "lpubsppop01.autoTimeStamp.luxonFormat": "dd.LL.yyyy HH:mm:ss",
    "lpubsppop01.autoTimeStamp.modifiedTimeEnd": "($| \\*/)",
}
```

**Comment by githuppi** [comment]
Hi @lpubsppop01 and thanks for your message. Could you please check again?

This leads to an open end uncommenting the whole code.

```
/* Created: 09.10.2023 12:24:41 */
/* Last modified: 16.10.2023 17:20:57
```

**Comment by githuppi** [comment]
Found the soultion with the help of regexr.com:

```
    "lpubsppop01.autoTimeStamp.birthTimeEnd": "($| \\*/)",
    "lpubsppop01.autoTimeStamp.luxonFormat": "dd.LL.yyyy HH:mm:ss",
    "lpubsppop01.autoTimeStamp.modifiedTimeEnd": "($| \*\/)",
```

Thanks a lot for providing such a neat extension 😄
