### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by SeaDude** [lpubsppop01/vscode-auto-timestamp#2]
Is there a setting that needs to be configured to use this Extension? When I save a document, nothing happens. 

I expected this Extension to add the following fields to my doc on FIRST save: 

```
//Created: <created date and time>
//Last Modified: <now date and time>
```

Then update the `//Last Modified:` upon subsequent saves. 

Can you assist me in understanding how to use the tool?

Thank you

**Comment by lpubsppop01** [comment]
Hi, @SeaDude.
Thank you for your feedback.

Does the document contain `"Created: "` and `"Last modified: "`?
This extension adds or updates only datetime text (`"<created date and time>"` and `"<now date and time>"`).

**Comment by SeaDude** [comment]
Hello,

aha! I was trying the literal examples shown in the docs: 
   ```
 // Created: 
    // Last modified: 
```

Changing this to: 
   ```
 Created:
    Last modified: 
```

Worked. Sorry for bothering you :)
