### ISSUE TITLE
modifiedTimeStart does not apply

### ISSUE THREAD

**Issue by minj** [lpubsppop01/vscode-auto-timestamp#4]
Config:
```json
	"lpubsppop01.autoTimeStamp.momentFormat": "YYYY-MM-DD HH:mm:ssZZ",
	"lpubsppop01.autoTimeStamp.modifiedTimeStart": "foobar: ",
```

File:
```
foobar: 2019-11-03 13:56:17+0100
Last modified: 2019-11-03 13:56:17+0100
```

-> save file:

```
foobar: 2019-11-03 13:56:17+0100
Last modified: 2019-11-03 13:58:20+0100
```

As you can see, the timestamps are out of sync after copy. Clearly, `lpubsppop01.autoTimeStamp.modifiedTimeStart` is completely ignored and replaced with default

**Comment by lpubsppop01** [comment]
Thanks for your feedback, @minj.

It seems that the cached regular expression is not cleared.
I will try to fix it when I have time, but for now please avoid it by reloading.

**Comment by minj** [comment]
I can confirm. Works after reload. Thanks.
