### ISSUE TITLE
workspace settings not overriding global settings

### ISSUE THREAD

**Issue by poblabs** [lpubsppop01/vscode-auto-timestamp#9]
Hi, when I change workspace settings, the extension is only looking at global settings. How can we update this?

**Comment by lpubsppop01** [comment]
Hi @poblabs.
Thank you for your feedback, and sorry for the very late reply.

It didn't seem to mean that the workspace settings wouldn't override the user settings.
But I found a similar problem:
- It seems that this extension is also working on workspace settings (`.vscode/settings.json`).
- The pattern string itself may be unintentionally updated, resulting in an invalid state.
- It will be detected as an error and the user setting will be used.

I fixed this issue in v0.0.5.
If you are still using this extension, please check it out when you have time.
